"""added updated_at in review+book

Revision ID: 023ca3918fe3
Revises: 14359a9c7e8f
Create Date: 2025-07-29 15:13:46.162404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023ca3918fe3'
down_revision = '14359a9c7e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RatingsReviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('book_manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_manager', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('RatingsReviews', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
