"""Add status field to Book model

Revision ID: 14359a9c7e8f
Revises: c7f6a88913b0
Create Date: 2025-07-28 15:36:11.927479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14359a9c7e8f'
down_revision = 'c7f6a88913b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=False, server_default='wishlist')
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_manager', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
