"""Added was_admin field to user model to track past admins

Revision ID: 154153748d71
Revises: 
Create Date: 2025-07-22 11:31:32.361209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154153748d71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('was_admin', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_db', schema=None) as batch_op:
        batch_op.drop_column('was_admin')

    # ### end Alembic commands ###
