"""added created_at and a new schema

Revision ID: c7f6a88913b0
Revises: 154153748d71
Create Date: 2025-07-26 19:39:23.815256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f6a88913b0'
down_revision = '154153748d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RatingsReviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('book_manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_manager', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('RatingsReviews', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
